### ISSUE TITLE
Make the client cloneable

### ISSUE THREAD

**Issue by gus4rs** [Mlemix/critter#1]
it should be possible to make the struct ```TwitterClient``` to ```#[derive(Clone)]``` and thus allow some degree of reuse of the same client across multiple threads, since the internal http client is cloneable and also an ```Arc```.
Apart from the http client, the only internal state of TwitterClient is ```TwitterAuth```, a bag of credentials that is immutable

**Comment by Mlemix** [comment]
Done in v0.1.75
