### ISSUE TITLE
Fail to tweet with video

### ISSUE THREAD

**Issue by gus4rs** [Mlemix/critter#2]
I am trying to post a Tweet with single 1.6 Mb mp4 video (tweeting with image works fine), the method ```upload_media``` executes with no error and returns:

```
{ media_id: 1671895180818132993, media_id_string: "1671895180818132993", expires_after_secs: Some(86400), processing_info: None }
```

When trying to Tweet referring this media_id, it doesn't work and doesn't show the error either, instead return a generic error 
``` HTTP request error: error decoding response body: missing field `code` at line 1 column 109'```

I put some println! in the library to catch the raw response from twitter API and the real error is it says the media_id obtained earlier  is invalid.

I inspect in the chunked upload and it seems to be calling the methods correctly. it sends a INIT, then two APPEND, and a FINALIZE, but the FINALIZE does not contain the field ```processing_info```:

```
[DEBUG] Finalize response: TwitterMediaResponse { media_id: 1671895180818132993, media_id_string: "1671895180818132993", expires_after_secs: Some(86400), processing_info: None }
```

This causes the ```upload_media``` to skip the upload status checking, and I think something is wrong in this media upload that is preventing me from sending the Tweet.

Another thing, I can manually post the tweet with the video, and using other Rust Twitter client ```egg_mode``` it works fine for this media

**Comment by Mlemix** [comment]
I just tried uploading a 3mb file and it also returned no processing info.
```
finalize: TwitterMediaResponse { media_id: 1671914083405250568, media_id_string: "1671914083405250568", expires_after_secs: Some(86400), processing_info: None }
```
However, the tweet was posted fine.

Did you provide an url or a path to a file?
Did you provide the wrong file extensions while trying to upload the video? (pic.jpg)
```rust
twitter.upload_media("/path/to/file.mp4", Some("pic.jpg".into()))
```

**Comment by gus4rs** [comment]
I provided the path to a file. Regarding the ```filename``` it's not really used with chunked upload, the mime is detected using the magic. In my case, the mime was correctly detected as ```video/mp4```

**Comment by gus4rs** [comment]
Here's the full code:

```rust
use std::env;
use critter::auth::TwitterAuth;
use critter::TwitterClient;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let auth = TwitterAuth::from_oa1uc(
        "xxx",
        "xxxx",
        "xxxx",
        "xxxx",
    );

    let mut twitter = TwitterClient::new(auth)?;

    let mut response = twitter
        .upload_media("/Users/xxx/videos/floppa.mp4", Some("floppa.mp4".to_string())).await?;

    let id = &response.id();

    match twitter.tweet(|tweet|
        tweet.text("text").media(|mb| mb.id(id.parse().unwrap())
        )
    ).await {
        Ok(data) => println!("Tweet id: {:?}", data.id()),
        Err(e) => println!("Error: {}", e)
    }

    Ok(())
}
```

The error is:
```
Error: HTTP request error: error decoding response body: missing field `code` at line 1 column 109
```

The video file is attached:

https://github.com/Mlemix/critter/assets/110654587/6a6da75b-ade0-4db7-b2f9-d14dacd4c9d7

**Comment by gus4rs** [comment]
It's also not a problem with my credentials. If I use a python 10-line script with the same file and same credentials it manages to upload the video correctly:

```python
import tweepy

consumer_key = "xxx"
consumer_secret = "xxx"
access_token = "xx-xx"
access_token_secret = "xx"

client = tweepy.Client(
    consumer_key=consumer_key, consumer_secret=consumer_secret,
    access_token=access_token, access_token_secret=access_token_secret
)

auth = tweepy.OAuth1UserHandler(consumer_key, consumer_secret, access_token, access_token_secret)

api = tweepy.API(auth)

media = api.media_upload("/Users/xxx/videos/floppa.mp4", chunked=True, media_category="tweet_video")

client.create_tweet(text="text",media_ids=[media.media_id])

```

**Comment by Mlemix** [comment]
Fixed.

The "missing field code" error occurred because Twitter doesn't actually return the `code` field with every response message and I've now made it optional.

Then, after inspecting the actual twitter API calls in console, it appears that I have to enable `allow_async` to get processing info.
![allow_async](https://cdn.discordapp.com/attachments/1106318901459034233/1121817255878066276/image.png)

You can now post your floppas without issues 😼. (though you must update to 0.1.75)

**Comment by gus4rs** [comment]
Awesome. And you fixed it just in time for Floppa Friday lmao.

**Comment by gus4rs** [comment]
btw, I checked the code against the API docs and could not find ```allow_async``` https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload-finalize

**Comment by gus4rs** [comment]
Oh, so it mentions ```This behavior is enabled if an upload session was [initialized](https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload-init) with a media_category parameter, and when then media type is either video or animated GIF```

If Critters sent a ```media_category``` in the INIT request, then maybe the new "undocumented" param wouldn't be needed. 

Anyway, I can confirm that the new version works fine

**Comment by gus4rs** [comment]
This is how some popular libraries handle errors:

Tweepy: navigate the mess and grab all text available, gluing it together. Do a best effort to capture the code too 😀

```python


        errors = response_json.get("errors", [])

        # Use := when support for Python 3.7 is dropped
        if "error" in response_json:
            errors.append(response_json["error"])

        error_text = ""

        for error in errors:
            self.api_errors.append(error)

            if isinstance(error, str):
                self.api_messages.append(error)
                error_text += '\n' + error
                continue

            if "code" in error:
                self.api_codes.append(error["code"])
            if "message" in error:
                self.api_messages.append(error["message"])

            if "code" in error and "message" in error:
                error_text += f"\n{error['code']} - {error['message']}"
            elif "message" in error:
                error_text += '\n' + error["message"]

   # Use := when support for Python 3.7 is dropped
        if not error_text and "detail" in response_json:
            self.api_messages.append(response_json["detail"])
            error_text = '\n' + response_json["detail"]

```

```twitter-v2``` has a catch-all ```HashMap``` plus some fixed field, modelled like this:

```rust
pub errors: Option<Vec<ApiError>>,

pub struct ApiError {
    pub title: String,
    #[serde(rename = "type")]
    pub kind: String,
    #[serde(default, with = "crate::utils::serde::status_code")]
    pub status: StatusCode,
    #[serde(default)]
    pub detail: String,
    #[serde(default)]
    pub errors: Vec<ApiErrorItem>,
}

#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct ApiErrorItem {
    parameters: HashMap<String, Vec<serde_json::Value>>,
    message: String,
}
```
